title:            PJ Dietz
description:      'Coding and stuff.'
url:              http://pjdietz.com
baseurl:          /
author:
    name:         'PJ Dietz'
    email:        'pjdietz@gmail.com'

paginate:         5

kramdown:
    input: GFM
    hard_wrap: false
gems:
    - jekyll-gist
    - jekyll-paginate
